import { z } from 'zod'
import { randomUUID } from 'crypto'

// const adsInsightsMetrics = z.array(z.object({
// 	'ad_id': z.string(),
// 	'account_id': z.string(),
// 	'campaign_id': z.string(),
// 	'canvas_avg_view_percent': z.number().nullish(),
// 	'canvas_avg_view_time': z.number().nullish(),
// 	'clicks': z.number().nullish(),
// 	'cost_per_estimated_ad_recallers': z.number().nullish(),
// 	'cost_per_inline_link_click': z.number().nullish(),
// 	'cost_per_outbound_click': z.number().nullish(),
// 	'cost_per_page_engagement': z.number().nullish(),
// 	'cost_per_post_engagement': z.number().nullish(),
// 	'cost_per_rsvp': z.number().nullish(),
// 	'cost_per_thruplay': z.number().nullish(),
// 	'cost_per_unique_click': z.number().nullish(),
// 	'cost_per_unique_inline_link_click': z.number().nullish(),
// 	'cost_per_unique_outbound_click': z.number().nullish(),
// 	'cpc': z.number().nullish(),
// 	'cpm': z.number().nullish(),
// 	'cpp': z.number().nullish(),
// 	'ctr': z.number().nullish(),
// 	'estimated_ad_recall_rate': z.number().nullish(),
// 	'estimated_ad_recallers': z.number().nullish(),
// 	'frequency': z.number().nullish(),
// 	'full_view_impressions': z.number().nullish(),
// 	'full_view_reach': z.number().nullish(),
// 	'impressions': z.number().nullish(),
// 	'inline_link_click_ctr': z.number().nullish(),
// 	'inline_link_clicks': z.number().nullish(),
// 	'instant_experience_clicks_to_open': z.number().nullish(),
// 	'instant_experience_clicks_to_start': z.number().nullish(),
// 	'instant_experience_outbound_clicks': z.number().nullish(),
// 	'media_views': z.number().nullish(),
// 	'objective': z.string().nullish(),
// 	'onsite_conversion_post_save': z.number().nullish(),
// 	'outbound_clicks': z.number().nullish(),
// 	'outbound_clicks_ctr': z.number().nullish(),
// 	'reach': z.number().nullish(),
// 	'spend': z.number().nullish(),
// 	'unique_clicks': z.number().nullish(),
// 	'unique_ctr': z.number().nullish(),
// 	'unique_inline_link_click_ctr': z.number().nullish(),
// 	'unique_inline_link_clicks': z.number().nullish(),
// 	'unique_outbound_clicks': z.number().nullish(),
// 	'unique_outbound_clicks_ctr': z.number().nullish(),
// }))

const metrics = Object.entries({
	// String fields
	'account_currency': z.string().nullish(),
	'account_id': z.string().nullish(),
	'account_name': z.string().nullish(),
	'activity_recency': z.string().nullish(),
	'ad_format_asset': z.string().nullish(),
	'ad_id': z.string().nullish(),
	'ad_name': z.string().nullish(),
	'adset_id': z.string().nullish(),
	'adset_name': z.string().nullish(),
	'age_targeting': z.string().nullish(),
	'attribution_setting': z.string().nullish(),
	'body_asset': z.string().nullish(),
	'buying_type': z.string().nullish(),
	'campaign_id': z.string().nullish(),
	'campaign_name': z.string().nullish(),
	'comparison_node': z.string().nullish(),
	'country': z.string().nullish(),
	'created_time': z.string().nullish(),
	'date_start': z.string().nullish(),
	'date_stop': z.string().nullish(),
	'description_asset': z.string().nullish(),
	'device_platform': z.string().nullish(),
	'dma': z.string().nullish(),
	'fidelity_type': z.string().nullish(),
	'gender_targeting': z.string().nullish(),
	'hourly_stats_aggregated_by_advertiser_time_zone': z.string().nullish(),
	'hourly_stats_aggregated_by_audience_time_zone': z.string().nullish(),
	'hsid': z.string().nullish(),
	'image_asset': z.string().nullish(),
	'impression_device': z.string().nullish(),
	'labels': z.string().nullish(),
	'landing_destination': z.string().nullish(),
	'location': z.string().nullish(),
	'media_asset': z.string().nullish(),
	'objective': z.string().nullish(),
	'optimization_goal': z.string().nullish(),
	'place_page_id': z.string().nullish(),
	'place_page_name': z.string().nullish(),
	'platform_position': z.string().nullish(),
	'product_id': z.string().nullish(),
	'publisher_platform': z.string().nullish(),
	'rule_asset': z.string().nullish(),
	'skan_version': z.string().nullish(),
	'title_asset': z.string().nullish(),
	'updated_time': z.string().nullish(),
	'user_segment_key': z.string().nullish(),
	'video_asset': z.string().nullish(),

	// Number fields
	'auction_bid': z.number().nullish(),
	'auction_competitiveness': z.number().nullish(),
	'auction_max_competitor_bid': z.number().nullish(),
	'canvas_avg_view_percent': z.number().nullish(),
	'canvas_avg_view_time': z.number().nullish(),
	'clicks': z.number().nullish(),
	'coarse_conversion_value': z.number().nullish(),
	'converted_product_quantity': z.number().nullish(),
	'converted_product_value': z.number().nullish(),
	'cost_per_15_sec_video_view': z.number().nullish(),
	'cost_per_2_sec_continuous_video_view': z.number().nullish(),
	'cost_per_ad_click': z.number().nullish(),
	'cost_per_dda_countby_convs': z.number().nullish(),
	'cost_per_inline_link_click': z.number().nullish(),
	'cost_per_inline_post_engagement': z.number().nullish(),
	'cost_per_one_thousand_ad_impression': z.number().nullish(),
	'cost_per_outbound_click': z.number().nullish(),
	'cost_per_thruplay': z.number().nullish(),
	'cost_per_unique_click': z.number().nullish(),
	'cost_per_unique_conversion': z.number().nullish(),
	'cost_per_unique_inline_link_click': z.number().nullish(),
	'cost_per_unique_outbound_click': z.number().nullish(),
	'cpc': z.number().nullish(),
	'cpm': z.number().nullish(),
	'cpp': z.number().nullish(),
	'ctr': z.number().nullish(),
	'dda_countby_convs': z.number().nullish(),
	'dda_results': z.number().nullish(),
	'estimated_ad_recall_rate_lower_bound': z.number().nullish(),
	'estimated_ad_recall_rate_upper_bound': z.number().nullish(),
	'estimated_ad_recallers_lower_bound': z.number().nullish(),
	'estimated_ad_recallers_upper_bound': z.number().nullish(),
	'frequency': z.number().nullish(),
	'frequency_value': z.number().nullish(),
	'full_view_impressions': z.number().nullish(),
	'full_view_reach': z.number().nullish(),
	'impressions': z.number().nullish(),
	'inline_link_click_ctr': z.number().nullish(),
	'inline_link_clicks': z.number().nullish(),
	'inline_post_engagement': z.number().nullish(),
	'instagram_upcoming_event_reminders_set': z.number().nullish(),
	'instant_experience_clicks_to_open': z.number().nullish(),
	'instant_experience_clicks_to_start': z.number().nullish(),
	'instant_experience_outbound_clicks': z.number().nullish(),
	'interactive_component_tap': z.number().nullish(),
	'marketing_messages_delivery_rate': z.number().nullish(),
	'outbound_clicks_ctr': z.number().nullish(),
	'postback_sequence_index': z.number().nullish(),
	'qualifying_question_qualify_answer_rate': z.number().nullish(),
	'reach': z.number().nullish(),
	'redownload': z.number().nullish(),
	'result_values_performance_indicator': z.number().nullish(),
	'shops_assisted_purchases': z.number().nullish(),
	'social_spend': z.number().nullish(),
	'spend': z.number().nullish(),
	'wish_bid': z.number().nullish(),

	// Fields with action_type/value pattern
	'action_values': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'actions': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'ad_click_actions': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'ad_impression_actions': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'catalog_segment_actions': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'catalog_segment_value': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'catalog_segment_value_mobile_purchase_roas': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'catalog_segment_value_omni_purchase_roas': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'catalog_segment_value_website_purchase_roas': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'conversion_values': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'conversions': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'cost_per_action_type': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'cost_per_conversion': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'cost_per_unique_action_type': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'mobile_app_purchase_roas': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'outbound_clicks': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'purchase_roas': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'video_30_sec_watched_actions': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'video_avg_time_watched_actions': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'video_continuous_2_sec_watched_actions': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'video_p100_watched_actions': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'video_p25_watched_actions': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'video_p50_watched_actions': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'video_p75_watched_actions': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'video_p95_watched_actions': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'video_play_actions': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'video_play_curve_actions': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'video_play_retention_0_to_15s_actions': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'video_play_retention_20_to_60s_actions': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'video_play_retention_graph_actions': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'video_time_watched_actions': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'website_ctr': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
	'website_purchase_roas': z.array(z.object({ action_type: z.string(), value: z.number() })).nullish(),
})
.filter(([key, value]) => ![
	'age_targeting', 
	'gender_targeting', 
	'labels', 
	'location', 
	'estimated_ad_recall_rate_lower_bound', 
	'estimated_ad_recall_rate_upper_bound', 
	'estimated_ad_recallers_lower_bound', 
	'estimated_ad_recallers_upper_bound',
].includes(key))	// (#100) <fields in the list above> are not valid for fields param after V19.0
.filter(([key, value]) => ![
	'activity_recency', 
	'ad_format_asset', 
	'body_asset', 
	'comparison_node', 
	'country', 
	'description_asset', 
	'device_platform', 
	'dma', 
	'fidelity_type', 
	'hourly_stats_aggregated_by_advertiser_time_zone', 
	'hourly_stats_aggregated_by_audience_time_zone', 
	'hsid', 
	'image_asset', 
	'impression_device', 
	'landing_destination', 
	'media_asset', 
	'place_page_id', 
	'platform_position', 
	'product_id', 
	'publisher_platform', 
	'rule_asset', 
	'skan_version', 
	'title_asset', 
	'user_segment_key', 
	'video_asset', 
	'coarse_conversion_value', 
	'frequency_value', 
	'postback_sequence_index', 
	'redownload',
].includes(key))	// (#100) <fields in the list above> are not valid for fields param. please check https://developers.facebook.com/docs/marketing-api/reference/ads-insights/ for all valid values
.reduce((acc, [key, value]) => ({...acc, [key]: value}), {})

const metricNames = {
	'account_currency': 'Account Currency',
	'account_id': 'Account ID',
	'account_name': 'Account Name',
	'activity_recency': 'Activity Recency',
	'ad_format_asset': 'Ad Format Asset',
	'ad_id': 'Ad ID',
	'ad_name': 'Ad Name',
	'adset_id': 'Ad Set ID',
	'adset_name': 'Ad Set Name',
	'age_targeting': 'Age Targeting',
	'attribution_setting': 'Attribution Setting',
	'body_asset': 'Body Asset',
	'buying_type': 'Buying Type',
	'campaign_id': 'Campaign ID',
	'campaign_name': 'Campaign Name',
	'comparison_node': 'Comparison Node',
	'country': 'Country',
	'created_time': 'Created Time',
	'date_start': 'Date Start',
	'date_stop': 'Date Stop',
	'description_asset': 'Description Asset',
	'device_platform': 'Device Platform',
	'dma': 'DMA',
	'fidelity_type': 'Fidelity Type',
	'gender_targeting': 'Gender Targeting',
	'hourly_stats_aggregated_by_advertiser_time_zone': 'Hourly Stats Aggregated by Advertiser Time Zone',
	'hourly_stats_aggregated_by_audience_time_zone': 'Hourly Stats Aggregated by Audience Time Zone',
	'hsid': 'HSID',
	'image_asset': 'Image Asset',
	'impression_device': 'Impression Device',
	'labels': 'Labels',
	'landing_destination': 'Landing Destination',
	'location': 'Location',
	'media_asset': 'Media Asset',
	'objective': 'Objective',
	'optimization_goal': 'Optimization Goal',
	'place_page_id': 'Place Page ID',
	'place_page_name': 'Place Page Name',
	'platform_position': 'Platform Position',
	'product_id': 'Product ID',
	'publisher_platform': 'Publisher Platform',
	'rule_asset': 'Rule Asset',
	'skan_version': 'SKAN Version',
	'title_asset': 'Title Asset',
	'updated_time': 'Updated Time',
	'user_segment_key': 'User Segment Key',
	'video_asset': 'Video Asset',
	'auction_bid': 'Auction Bid',
	'auction_competitiveness': 'Auction Competitiveness',
	'auction_max_competitor_bid': 'Auction Max Competitor Bid',
	'canvas_avg_view_percent': 'Canvas Avg View Percent',
	'canvas_avg_view_time': 'Canvas Avg View Time',
	'clicks': 'Clicks',
	'coarse_conversion_value': 'Coarse Conversion Value',
	'converted_product_quantity': 'Converted Product Quantity',
	'converted_product_value': 'Converted Product Value',
	'cost_per_15_sec_video_view': 'Cost per 15 Sec Video View',
	'cost_per_2_sec_continuous_video_view': 'Cost per 2 Sec Continuous Video View',
	'cost_per_ad_click': 'Cost per Ad Click',
	'cost_per_dda_countby_convs': 'Cost per DDA Count by Convs',
	'cost_per_inline_link_click': 'Cost per Inline Link Click',
	'cost_per_inline_post_engagement': 'Cost per Inline Post Engagement',
	'cost_per_one_thousand_ad_impression': 'Cost per One Thousand Ad Impression',
	'cost_per_outbound_click': 'Cost per Outbound Click',
	'cost_per_thruplay': 'Cost per Thruplay',
	'cost_per_unique_click': 'Cost per Unique Click',
	'cost_per_unique_conversion': 'Cost per Unique Conversion',
	'cost_per_unique_inline_link_click': 'Cost per Unique Inline Link Click',
	'cost_per_unique_outbound_click': 'Cost per Unique Outbound Click',
	'cpc': 'CPC',
	'cpm': 'CPM',
	'cpp': 'CPP',
	'ctr': 'CTR',
	'dda_countby_convs': 'DDA Count by Convs',
	'dda_results': 'DDA Results',
	'estimated_ad_recall_rate_lower_bound': 'Estimated Ad Recall Rate Lower Bound',
	'estimated_ad_recall_rate_upper_bound': 'Estimated Ad Recall Rate Upper Bound',
	'estimated_ad_recallers_lower_bound': 'Estimated Ad Recallers Lower Bound',
	'estimated_ad_recallers_upper_bound': 'Estimated Ad Recallers Upper Bound',
	'frequency': 'Frequency',
	'frequency_value': 'Frequency Value',
	'full_view_impressions': 'Full View Impressions',
	'full_view_reach': 'Full View Reach',
	'impressions': 'Impressions',
	'inline_link_click_ctr': 'Inline Link Click CTR',
	'inline_link_clicks': 'Inline Link Clicks',
	'inline_post_engagement': 'Inline Post Engagement',
	'instagram_upcoming_event_reminders_set': 'Instagram Upcoming Event Reminders Set',
	'instant_experience_clicks_to_open': 'Instant Experience Clicks to Open',
	'instant_experience_clicks_to_start': 'Instant Experience Clicks to Start',
	'instant_experience_outbound_clicks': 'Instant Experience Outbound Clicks',
	'interactive_component_tap': 'Interactive Component Tap',
	'marketing_messages_delivery_rate': 'Marketing Messages Delivery Rate',
	'outbound_clicks_ctr': 'Outbound Clicks CTR',
	'postback_sequence_index': 'Postback Sequence Index',
	'qualifying_question_qualify_answer_rate': 'Qualifying Question Qualify Answer Rate',
	'reach': 'Reach',
	'redownload': 'Redownload',
	'result_values_performance_indicator': 'Result Values Performance Indicator',
	'shops_assisted_purchases': 'Shops Assisted Purchases',
	'social_spend': 'Social Spend',
	'spend': 'Spend',
	'wish_bid': 'Wish Bid',
	'action_values': 'Action Values',
	'actions': 'Actions',
	'ad_click_actions': 'Ad Click Actions',
	'ad_impression_actions': 'Ad Impression Actions',
	'catalog_segment_actions': 'Catalog Segment Actions',
	'catalog_segment_value': 'Catalog Segment Value',
	'catalog_segment_value_mobile_purchase_roas': 'Catalog Segment Value Mobile Purchase ROAS',
	'catalog_segment_value_omni_purchase_roas': 'Catalog Segment Value Omni Purchase ROAS',
	'catalog_segment_value_website_purchase_roas': 'Catalog Segment Value Website Purchase ROAS',
	'conversion_values': 'Conversion Values',
	'conversions': 'Conversions',
	'cost_per_action_type': 'Cost per Action Type',
	'cost_per_conversion': 'Cost per Conversion',
	'cost_per_unique_action_type': 'Cost per Unique Action Type',
	'mobile_app_purchase_roas': 'Mobile App Purchase ROAS',
	'outbound_clicks': 'Outbound Clicks',
	'purchase_roas': 'Purchase ROAS',
	'video_30_sec_watched_actions': 'Video 30 Sec Watched Actions',
	'video_avg_time_watched_actions': 'Video Avg Time Watched Actions',
	'video_continuous_2_sec_watched_actions': 'Video Continuous 2 Sec Watched Actions',
	'video_p100_watched_actions': 'Video P100 Watched Actions',
	'video_p25_watched_actions': 'Video P25 Watched Actions',
	'video_p50_watched_actions': 'Video P50 Watched Actions',
	'video_p75_watched_actions': 'Video P75 Watched Actions',
	'video_p95_watched_actions': 'Video P95 Watched Actions',
	'video_play_actions': 'Video Play Actions',
	'video_play_curve_actions': 'Video Play Curve Actions',
	'video_play_retention_0_to_15s_actions': 'Video Play Retention 0 to 15s Actions',
	'video_play_retention_20_to_60s_actions': 'Video Play Retention 20 to 60s Actions',
	'video_play_retention_graph_actions': 'Video Play Retention Graph Actions',
	'video_time_watched_actions': 'Video Time Watched Actions',
	'website_ctr': 'Website CTR',
	'website_purchase_roas': 'Website Purchase ROAS',
}

const PERIODS = {
	'daily': 'daily',
	'lifetime': 'lifetime',
}

const BREAKDOWNS = [
	['age', 'gender'],
	['country', 'region']
]

export { metricNames }

export default {

	metrics,

	metricNames,

	schemas: Object.keys(PERIODS).reduce((acc, period) => {
		BREAKDOWNS.forEach((breakdown) => {
			const breakdownName = breakdown.join('_')
			const tableName = `facebook_ads_insights_${period}_${breakdownName}`
			acc[tableName] = z.object({
				// social network identifiers
				user_id: z.string(),
				ad_account_id: z.string(),
				ad_id: z.string(),
				// our identifiers
				period: z.string().default(period),
				breakdowns: z.array(z.string()),
				uid: z.string().nullish().default(randomUUID),
				created_at: z.date().nullish().default(() => new Date()),
				// data
				insights: z.array(z.object({
					...metrics,
					...breakdown.reduce((acc, breakdown) => {
						acc[breakdown] = z.string().nullish()
						return acc
					}, {}),
				})),
			})
		})
		return acc
	}, {}),

}